### ISSUE TITLE
bad variable in terraform.tfvars

### ISSUE THREAD

**Issue by cobrin** [hashicorp/learn-terraform-vsphere#3]
The following lines in `terraform.tfvars` need correcting
```
vsphere_dc         = "PacketDatacenter"
datacenter         = "datastore1"
```
should read
```
datacenter          = "PacketDatacenter"
datastore           = "datastore1"
```

It might sensible to compare `terraform.tfvars` and `packer/vars.auto.pkrvars.hcl.example` to be similarly aligned for easy comparison

**Comment by im2nguyen** [comment]
Thanks for reporting this! 

We just updated the `terraform.tfvars.example` file so they use the right variable names 😄
