### ISSUE TITLE
error cloning virtual machine

### ISSUE THREAD

**Issue by telekomancer** [hashicorp/learn-terraform-vsphere#5]
After apply and, "yes" the following messages appears:

```
vsphere_virtual_machine.learn: Creating...
╷
│ Error: error cloning virtual machine: A specified parameter was not correct: spec.pool
│ 
│   with vsphere_virtual_machine.learn,
│   on main.tf line 34, in resource "vsphere_virtual_machine" "learn":
│   34: resource "vsphere_virtual_machine" "learn" {
│ 
```

**Comment by judithpatudith** [comment]
Thanks @telekomancer for the report! Our team is out for an offsite, but we'll look into it shortly!

**Comment by telekomancer** [comment]
?

**Comment by telekomancer** [comment]
Ok i solve myself the issue with the help of ![this link](https://communities.vmware.com/t5/VMware-vCenter-Discussions/vCSA-HA-failed-during-deployment/td-p/1383825)

I suggest that README.md should have some pre-requisites list, as i have a standalone (and only one) vSphere (Server and Hypervisor), some things don't apply, for example HA, well, for some weird reason, i must create an HA even when i have only one of both vSphere to work properly.

I guess that the error is more about VMware architecture than terraform itself, but terraform should have more info about that OR a KB related to this.

/close
